Repository cli/cli, pull requests merged in 2020-06, with the labels that each got.

#992 Query Params in Web mode of Issue/PR creation
  command/issue.go
  command/issue_test.go
  command/pr_create.go
Labels: community

#991 gh alias list
  command/alias.go
  command/alias_test.go
  internal/config/alias_config.go
Labels: aliases

#1103 gh alias delete
  command/alias.go
  command/alias_test.go
  command/root.go
  internal/config/alias_config.go
  internal/config/config_type.go
Labels: aliases

#1109 remove strict ">" when click link
  command/root.go
Labels: docs, needs-user-input

#950 Allow choosing a blank issue/pr template
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  command/issue.go
  command/pr_create.go
  command/title_body_survey.go
  pkg/githubtemplate/github_template.go
  pkg/githubtemplate/github_template_test.go
Labels: community

#1179 Issue #1178 - Direct users to https url for manual
  command/help.go
Labels: community

#994 Fix incorrect docs in Issue&PR create
  command/issue.go
  command/pr_create.go
Labels: community, enhancement

#1187 Issue #930 - Removing color for output files
  utils/color.go
Labels: community
