Repository cli/cli, pull requests merged in 2020-05, with the labels that each got.

#919 Improved error message when "owner/repo" format not provided
  api/queries_issue_test.go
  api/queries_repo_test.go
  command/repo.go
  command/root.go
  context/blank_context.go
  context/context.go
  internal/ghrepo/repo.go
Labels: community

#958 fix and tweak for site build
  .github/workflows/releases.yml
  Makefile
Labels: ci

#915 Generate manpages from cobra
  .gitignore
  .goreleaser.yml
  Makefile
  cmd/gen-docs/main.go
Labels: community, docs, packaging
