Repository cli/cli, pull requests merged in 2020-09, with the labels that each got.

#1640 Add auth command and flag usage to README
  README.md
Labels: docs

#1611 Prepend PR body defaults to the selected template (if any)
  pkg/cmd/pr/create/create_test.go
  pkg/cmd/pr/shared/title_body_survey.go
Labels: community

#1656 Add opensuse zypper installation steps
  docs/install_linux.md
Labels: community

#1652 Handle runtime error on bad user input
  cmd/gh/main.go
Labels: community

#1704 Go 1.15+ is required to run the test suit
  .github/CONTRIBUTING.md
Labels: community

#1049 hackday: gh repo garden
  pkg/cmd/repo/garden/garden.go
  pkg/cmd/repo/garden/http.go
  pkg/cmd/repo/repo.go
Labels: hack

#1696 Extract environment variables as a separate help topic
  pkg/cmd/root/help.go
  pkg/cmd/root/help_topic.go
  pkg/cmd/root/help_topic_test.go
  pkg/cmd/root/root.go
Labels: docs

#1699 bunch of gist stuff
  README.md
  internal/ghinstance/host.go
  pkg/cmd/alias/list/list.go
  pkg/cmd/gist/create/create.go
  pkg/cmd/gist/create/create_test.go
  pkg/cmd/gist/edit/edit.go
  pkg/cmd/gist/edit/edit_test.go
  pkg/cmd/gist/gist.go
  pkg/cmd/gist/list/http.go
  pkg/cmd/gist/list/list.go
  pkg/cmd/gist/list/list_test.go
  pkg/cmd/gist/shared/shared.go
  pkg/cmd/gist/view/view.go
  pkg/cmd/gist/view/view_test.go
Labels: gist

#1766 Added option to specify branch in gh repo view
  pkg/cmd/repo/view/http.go
  pkg/cmd/repo/view/view.go
  pkg/cmd/repo/view/view_test.go
Labels: community

#1856 Installation Guide on Linux - missing dependency
  docs/install_linux.md
Labels: community

#1877 Clarify Linux distros
  docs/install_linux.md
Labels: community

#1767 Fix debian executable path
  .goreleaser.yml
Labels: community

#1824 Use status codes from http package
  auth/oauth.go
Labels: community

#1888 fix: Capitalization and addition of `Enterprise` in install_linux
  docs/install_linux.md
Labels: community

#1889 Fixed gh pr checkout on detached HEAD
  pkg/cmd/pr/checkout/checkout.go
  pkg/cmd/pr/checkout/checkout_test.go
Labels: community

#1781 Fix gist ID extraction from url
  pkg/cmd/gist/edit/edit.go
  pkg/cmd/gist/shared/shared.go
  pkg/cmd/gist/shared/shared_test.go
  pkg/cmd/gist/view/view.go
  pkg/cmd/gist/view/view_test.go
Labels: community

#1891 Add Nix/NixOS instructions to install the package
  docs/install_linux.md
Labels: community

#1749 fix(browser): show message if $BROWSER isn't in $PATH
  pkg/browser/browser.go
  utils/utils.go
Labels: community

#1915 Modification of help text for usage of gh pr checks
  pkg/cmd/pr/checks/checks.go
Labels: community

#1967 Fix some bugs in `repo garden` in repositories with few commits
  pkg/cmd/repo/garden/garden.go
  pkg/cmd/repo/garden/http.go
Labels: community
