Repository cli/cli, pull requests merged in 2021-11, with the labels that each got.

#4450 gh repo rename
  git/remote.go
  pkg/cmd/repo/rename/http.go
  pkg/cmd/repo/rename/rename.go
  pkg/cmd/repo/rename/rename_test.go
  pkg/cmd/repo/repo.go
Labels: enhancement, core

#4610 Don't use gpg in Debian instruction
  docs/install_linux.md
Labels: hacktoberfest-accepted

#4578 rewrite `gh repo create`
  git/git.go
  pkg/cmd/repo/create/create.go
  pkg/cmd/repo/create/create_test.go
Labels: enhancement, tech debt

#4562 Confirm name change before creating a repo with special characters
  pkg/cmd/repo/create/create.go
  pkg/cmd/repo/create/create_test.go
Labels: hacktoberfest-accepted

#4434 update help for magic type conversion #4365
  pkg/cmd/api/api.go
Labels: hacktoberfest-accepted
