Repository cli/cli, pull requests merged in 2021-12, with the labels that each got.

#4423 - Add new flag --no-store to print the encoded secret in "secret set"
  pkg/cmd/secret/set/set.go
  pkg/cmd/secret/set/set_test.go
Labels: hacktoberfest-accepted

#4842 gh cs cp --help: fix typo
  pkg/cmd/codespace/ssh.go
Labels: external

#4847 gist view: fix missing files shorthand
  pkg/cmd/gist/view/view.go
Labels: external

#4467 Add `--generate-notes` flag to `gh release create` command.
  pkg/cmd/gist/edit/edit.go
  pkg/cmd/pr/merge/merge.go
  pkg/cmd/pr/shared/commentable.go
  pkg/cmd/release/create/create.go
  pkg/cmd/release/create/create_test.go
  pkg/cmd/release/create/http.go
  pkg/surveyext/editor_manual.go
Labels: hacktoberfest-accepted

#4525 Iss 3987 interactive gh create release
  pkg/cmd/release/create/create.go
  pkg/cmd/release/create/create_test.go
  pkg/cmd/release/create/http.go
Labels: hacktoberfest-accepted

#4861 fix race condition when updating labels
  pkg/cmd/issue/edit/edit_test.go
  pkg/cmd/pr/edit/edit.go
  pkg/cmd/pr/edit/edit_test.go
  pkg/cmd/pr/shared/editable.go
  pkg/cmd/pr/shared/editable_http.go
Labels: external

#4845 allow users to open up the last commit of a repository while using repo override flag
  api/queries_repo.go
  pkg/cmd/browse/browse.go
  pkg/cmd/browse/browse_test.go
Labels: external

#4850 Made check symbol for cancelled uniform across commands
  pkg/cmd/run/list/list_test.go
  pkg/cmd/run/shared/shared.go
  pkg/cmd/workflow/view/view_test.go
Labels: external

#4857 upgrade local extension and up-to-date are not failures
  pkg/cmd/extension/command.go
  pkg/cmd/extension/command_test.go
  pkg/cmd/extension/manager.go
Labels: needs-user-input, external

#4920 Update StateDir comment to mention XDG_STATE_HOME.
  internal/config/config_file.go
Labels: external

#3869 Add `--json` export flag for workflow runs
  pkg/cmd/run/list/list.go
  pkg/cmd/run/shared/shared.go
  pkg/cmd/run/view/view.go
Labels: enhancement

#4931 docs: Installation instructions for pkgsrc
  docs/install_linux.md
Labels: external

#3344 Allow editing commit subject when squash-merging a PR
  pkg/cmd/pr/merge/http.go
  pkg/cmd/pr/merge/merge.go
  pkg/cmd/pr/merge/merge_test.go
  pkg/cmd/pr/shared/survey.go
Labels: enhancement, external

#4285 fix: #4263 show open prs only on default branch
  pkg/cmd/pr/shared/finder.go
  pkg/cmd/pr/shared/finder_test.go
Labels: external

#4534 Adding set secrets from env files
  go.mod
  go.sum
  pkg/cmd/secret/set/http.go
  pkg/cmd/secret/set/set.go
  pkg/cmd/secret/set/set_test.go
Labels: hacktoberfest-accepted, external
