Repository cli/cli, pull requests merged in 2023-09, with the labels that each got.

#7923 rename template to mark-template cmd
  pkg/cmd/project/mark-template/mark_template.go
  pkg/cmd/project/mark-template/mark_template_test.go
  pkg/cmd/project/project.go
Labels: external

#7873 `gh status`: show status even if a comment 404s
  pkg/cmd/status/status.go
  pkg/cmd/status/status_test.go
Labels: external

#7879 Fetch all jobs on a `gh view run` with `json` flag
  pkg/cmd/run/shared/shared.go
  pkg/cmd/run/shared/test.go
  pkg/cmd/run/view/view_test.go
Labels: external

#7900 Add all flag to 'gh alias delete'
  pkg/cmd/alias/delete/delete.go
  pkg/cmd/alias/delete/delete_test.go
Labels: external

#7884 feat: delete local tag when running `gh release delete --cleanup-tag`
  git/client.go
  git/client_test.go
  pkg/cmd/release/delete/delete.go
  pkg/cmd/release/delete/delete_test.go
Labels: external

#7983 Show full permissions URL in `gh cs create`
  pkg/cmd/codespace/create.go
  pkg/cmd/codespace/create_test.go
Labels: external, codespaces

#7861 Add `gh release create [<tag>] --notes-from-tag`
  pkg/cmd/release/create/create.go
  pkg/cmd/release/create/create_test.go
Labels: external

#7781 Document when gh auth login writes oauth token to plain text
  internal/config/config.go
  pkg/cmd/auth/login/login.go
  pkg/cmd/auth/refresh/refresh.go
  pkg/cmd/auth/shared/login_flow.go
  pkg/cmd/auth/shared/login_flow_test.go
Labels: external

#7961 Hint adding codespace scope to auth login
  pkg/cmd/root/root.go
Labels: external

#8030 cache/delete: percent-encode keys
  pkg/cmd/cache/delete/delete.go
  pkg/cmd/cache/delete/delete_test.go
Labels: external

#8037 Return HTTP errors properly for some commands
  pkg/cmd/gpg-key/delete/delete.go
  pkg/cmd/gpg-key/delete/delete_test.go
  pkg/cmd/run/watch/watch.go
  pkg/cmd/run/watch/watch_test.go
Labels: external

#7954 feat(cache): Add JSON exporting support for cache list
  pkg/cmd/cache/list/list.go
  pkg/cmd/cache/shared/shared.go
  pkg/cmd/cache/shared/shared_test.go
Labels: needs-user-input, external

#8082 Update triage documentation with link to unlabeled open issues
  docs/triage.md
Labels: external

#8023 Forward codespace ports over Dev Tunnels
  go.mod
  go.sum
  internal/codespaces/api/api.go
  internal/codespaces/codespaces.go
  internal/codespaces/connection/connection.go
  internal/codespaces/connection/connection_test.go
  internal/codespaces/connection/tunnels_api_server_mock.go
  internal/codespaces/portforwarder/port_forwarder.go
  internal/codespaces/portforwarder/port_forwarder_test.go
  pkg/cmd/codespace/common.go
  pkg/cmd/codespace/mock_api.go
  pkg/cmd/codespace/ports.go
  pkg/cmd/codespace/ports_test.go
Labels: external
